### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [term-world/bodega-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Reflection

- [ ] group-reflection.md has no TODO markers
- [ ] group-reflection.md contains at least 300 words
- [ ] group-reflection.md checkboxes checked attested to

## Bodega Site

- [ ] site&#x2F;_config.yml has no TODO markers
- [ ] about.md has no TODO markers
- [ ] More than one post exists in site&#x2F;_posts

## Stockroom Stocking

- [x] Individual reflections contain no TODO markers
- [ ] Example list file removed from stockroom
- [ ] Example department removed from stockroom
- [ ] Each department contains at least 10 items

## Percent complete

Based on the checks achieved, this assignment is `10%` complete.
